drop table "Fabryki" cascade constraints PURGE;
drop table "Jazdy_probne" cascade constraints PURGE;
drop table "Klienci" cascade constraints PURGE;
drop table "Leasingodawcy" cascade constraints PURGE;
drop table "Marki modeli" cascade constraints PURGE;
drop table "Modele" cascade constraints PURGE;
drop table "Pracownicy" cascade constraints PURGE;
drop table "Salony_Samochodowe" cascade constraints PURGE;
drop table "Salony_Samochodowe_Fabryki" cascade constraints PURGE;
drop table "Salony_Samochodowe_Klienci" cascade constraints PURGE;
drop table "Salony_Samochodowe_Samochody" cascade constraints PURGE;
drop table "Salony_Samochodowe_Uslugi" cascade constraints PURGE;
drop table "Samochody" cascade constraints PURGE;
drop table "Samochody_Uslugi" cascade constraints PURGE;
drop table "Sprzedaze_samochodow" cascade constraints PURGE;
drop table "Transakcje" cascade constraints PURGE;
drop table "Ubezpieczenia" cascade constraints PURGE;
drop table "Uslugi" cascade constraints PURGE;
drop table "Wlasciciele" cascade constraints PURGE;
drop table "Wynagrodzenia" cascade constraints PURGE;
drop table "Leasingi" cascade constraints PURGE;
drop table "Adresy" cascade constraints PURGE;

drop index "Unique_Identifier1";
drop index "Unique_Identifier10";
drop index "Unique_Identifier11";
drop index "Unique_Identifier18";
drop index "Unique_Identifier21";
drop index "Unique_Identifier22";
drop index "Unique_Identifier23";
drop index "Unique_Identifier24";
drop index "Unique_Identifier25";
drop index "Unique_Identifier3";
drop index "Unique_Identifier7";
drop index "Unique_Identifier8";
drop index "Unique_Identifier24";