drop table "MDOLICHE"."Fabryki" cascade constraints PURGE;
drop table "MDOLICHE"."Jazdy_probne" cascade constraints PURGE;
drop table "MDOLICHE"."Klienci" cascade constraints PURGE;
drop table "MDOLICHE"."Leasingodawcy" cascade constraints PURGE;
drop table "MDOLICHE"."Marki modeli" cascade constraints PURGE;
drop table "MDOLICHE"."Modele" cascade constraints PURGE;
drop table "MDOLICHE"."Pracownicy" cascade constraints PURGE;
drop table "MDOLICHE"."Salony_Samochodowe" cascade constraints PURGE;
drop table "MDOLICHE"."Salony_Samochodowe_Fabryki" cascade constraints PURGE;
drop table "MDOLICHE"."Salony_Samochodowe_Klienci" cascade constraints PURGE;
drop table "MDOLICHE"."Salony_Samochodowe_Samochody" cascade constraints PURGE;
drop table "MDOLICHE"."Salony_Samochodowe_Uslugi" cascade constraints PURGE;
drop table "MDOLICHE"."Samochody" cascade constraints PURGE;
drop table "MDOLICHE"."Samochody_Uslugi" cascade constraints PURGE;
drop table "MDOLICHE"."Sprzedaze_samochodow" cascade constraints PURGE;
drop table "MDOLICHE"."Transakcje" cascade constraints PURGE;
drop table "MDOLICHE"."Ubezpieczenia" cascade constraints PURGE;
drop table "MDOLICHE"."Uslugi" cascade constraints PURGE;
drop table "MDOLICHE"."Wlasciciele" cascade constraints PURGE;
drop table "MDOLICHE"."Wynagrodzenia" cascade constraints PURGE;
drop table "MDOLICHE"."Leasingi" cascade constraints PURGE;
drop table "MDOLICHE"."Adresy" cascade constraints PURGE;

drop index "MDOLICHE"."Unique_Identifier1";
drop index "MDOLICHE"."Unique_Identifier10";
drop index "MDOLICHE"."Unique_Identifier11";
drop index "MDOLICHE"."Unique_Identifier18";
drop index "MDOLICHE"."Unique_Identifier21";
drop index "MDOLICHE"."Unique_Identifier22";
drop index "MDOLICHE"."Unique_Identifier23";
drop index "MDOLICHE"."Unique_Identifier24";
drop index "MDOLICHE"."Unique_Identifier25";
drop index "MDOLICHE"."Unique_Identifier3";
drop index "MDOLICHE"."Unique_Identifier7";
drop index "MDOLICHE"."Unique_Identifier8";
drop index "MDOLICHE"."Unique_Identifier24";